name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MyFunction/requirements.txt

    - name: Set environment variables
      run: |
        echo "COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT  }}" >> $GITHUB_ENV
        echo "COSMOS_KEY=${{ secrets.COSMOS_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      env:
        COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
        COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
      run: |
        cd MyFunction/test
        pytest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group Resourceshahzaib --template-file Infrastructure/template.json --parameters Infrastructure/parameters.json
