name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the exact Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MyFunction/requirements.txt

    - name: Set environment variables
      run: |
        echo "COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}" >> $GITHUB_ENV
        echo "COSMOS_KEY=${{ secrets.COSMOS_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}" >> $GITHUB_ENV

    # Optional step to debug: Uncomment to print environment variables (remove this step in production)
    # - name: Show environment variables
    #   run: |
    #     echo "COSMOS_ENDPOINT: $COSMOS_ENDPOINT"
    #     echo "COSMOS_KEY: $COSMOS_KEY"

    - name: Run tests
      run: |
        cd MyFunction
        pytest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group resourceshahzaib --template-file template.json --parameters parameters.json
